services:

  nginx:
    build:
      context: ./nginx
      args:
        ENVIRONMENT: dev
    depends_on:
      - frontend
  # Adiciona o serviço do Postgres apenas para o ambiente local
  
  db:
    image: postgres:16
    container_name: postgres_db
    env_file:
      - .env.dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Adiciona o serviço do frontend
  frontend:
    build:
      context: ./front/front-sistema-de-gestao-prefeituras
      args:
        NEXT_PUBLIC_API_URL: http://localhost/api
    # A porta agora é acessada apenas pela rede interna do Docker, através do Nginx
    # ports:
    #   - "80:3000" 
    restart: always
    environment:
      # O frontend agora fala com a API através do Nginx
      - NEXT_PUBLIC_API_URL=http://localhost/api
    depends_on:
      - backend

  # Adiciona uma dependência no backend para que ele espere o mysql iniciar
  backend:
    depends_on:
      - db
    env_file:
      - .env.dev

# Define um volume nomeado para que os dados do Postgres não se percam
# quando o contêiner for recriado
volumes:
  postgres_data:
