package com.planmanager.www.model.propostas;

public enum Plano {
    UM("PLANO MUNICIPAL DE PROMOÇÃO, PROTEÇÃO E DEFESA DO DIREITO DE CONVIVÊNCIA FAMILIAR E COMUNITÁRIA DE CRIANÇAS E ADOELSCENTES"),
    DOIS("PLANO DA PRIMEIRA INFÂNCIA"),
    TRES("PLANO DE PREVENÇÃO E ERRADICAÇÃO DO TRABALHO INFANTIL E PROTEÇÃO AO ADOLESCENTE TRABALHADOR"),
    QUATRO("PLANO DE ENFRENTAMENTO DA VIOLÊNCIA SEXUAL CONTRA CRIANÇAS E ADOLESCENTES"),
    CINCO("PLANO MUNICIPAL DE ATENDIMENTO SOCIOEDUCATIVO"),
    SEIS("PLANO MUNICIPAL DE PREVENÇÃO E ATENDIMENTO DE CRIANÇAS E ADOLESCENTES VÍTIMAS OU TESTEMUNHAS DE VIOLÊNCIA");

    private final String titulo;

    Plano(String titulo) {
        this.titulo = titulo;
    }

    public String getTitulo() {
        return titulo;
    }
}
